--- linux-2.6.28.10/arch/arm/include/asm/soc-ast/debug-macro.S	1970-01-01 08:00:00.000000000 +0800
+++ linux-2.6.28.10-ami/arch/arm/include/asm/soc-ast/debug-macro.S	2010-05-10 16:33:31.000000000 +0800
@@ -0,0 +1,53 @@
+/* linux/include/asm-arm/arch-xxx/debug-macro.S
+ *
+ * Debugging macro include header
+ *
+ * Copyright (C) 1994-1999 Russell King
+ *
+ * Ported for ASPEED SOC (Base code taken from arch-integrator)
+ * Copyright (C) 2005 American Megatrends Inc.
+ *
+ * This program is free software; you can redistribute it and/or modify
+ * it under the terms of the GNU General Public License version 2 as
+ * published by the Free Software Foundation.
+ *
+*/
+
+#include <mach/lowlevel_serial.h>
+
+uart_base:
+		.word  UART_BASE
+uart_mmu_base:
+		.word   UART_MMU_BASE
+
+mmu_enabled:
+		.word	io_mapping_done
+
+		.macro	addruart,rx
+		ldr		\rx, mmu_enabled
+		ldr		\rx,[\rx]
+		tst		\rx, #1				@ MMU enabled (paging init done)?
+		beq		1001f
+		ldr		\rx, uart_mmu_base 	@ virtual address
+		b		1002f
+1001:
+		ldr		\rx, uart_base	 	@	 physical address
+1002:
+		.endm
+
+		.macro	senduart,rd,rx
+		strb	\rd, [\rx, #SERIAL_THR]
+		.endm
+
+		.macro	waituart,rd,rx
+1001:	ldr		\rd, [\rx, #SERIAL_LSR]
+		tst		\rd, #1 << 5			@ UART_LSR_THRE
+		beq		1001b
+		.endm
+
+/* I dont know what busyuart should do. So I used the same as waituart */
+		.macro	busyuart,rd,rx
+1001:	ldr		\rd, [\rx, #SERIAL_LSR]
+		tst		\rd, #1 << 5			@ UART_LSR_THRE
+		beq		1001b
+		.endm
