DEBUG := n
TARGET := watchdog_hw
OBJS := ast_watchdog.o

EXTRA_CFLAGS += -I${SPXINC}/global
EXTRA_CFLAGS += -I${SPXINC}/helper
EXTRA_CFLAGS += -I${SPXINC}/watchdog

-include ${TOOLDIR}/rules/Rules.make.drivers
