DEBUG := n
TARGET := gpio_hw
OBJS := gpiomain_hw.o 

EXTRA_CFLAGS += -I${SPXINC}/global
EXTRA_CFLAGS += -I${SPXINC}/helper
EXTRA_CFLAGS += -I${SPXINC}/gpio

-include ${TOOLDIR}/rules/Rules.make.drivers

