DEBUG     := n
TARGET    := jtag
OBJS      := jtagmain.o

EXTRA_CFLAGS += -I${SPXINC}/global
EXTRA_CFLAGS += -I${SPXINC}/dbgout
EXTRA_CFLAGS += -I${SPXINC}/helper

-include ${TOOLDIR}/rules/Rules.make.drivers

