DEBUG := n
TARGET := snoop_hw
OBJS := ast_snoop.o

EXTRA_CFLAGS += -I${SPXINC}/global
EXTRA_CFLAGS += -I${SPXINC}/helper
EXTRA_CFLAGS += -I${SPXINC}/snoop

-include ${TOOLDIR}/rules/Rules.make.drivers
