#----------------------------------------------------------------------
#                      Makefile to build libami dbgout
#                 Copyright (c) 2008 American Megatrends Inc 
#-----------------------------------------------------------------------

#------- Comment/uncomment the following line to enable/disable debugging--------------
DEBUG = n

#---------------------- Change according to your files ----------------------------------
LIBRARY_NAME 	= libiniparser
SRC 		= dictionary.c iniparser.c strlib.c parse-ex.c	 # Source File

CFLAGS += -I${SPXINC}/iniparser

#----------------------------------------------------------------------------------------
include ${TOOLDIR}/rules/Rules.make.libs
