DEBUG     := n
TARGET	  := cipher_hw
OBJS      := ast_cipher.o aes_core.o rc4.o

EXTRA_CFLAGS += -I${SPXINC}/global
EXTRA_CFLAGS += -I${SPXINC}/helper
EXTRA_CFLAGS += -I${SPXINC}/cipher


-include ${TOOLDIR}/rules/Rules.make.drivers

