DEBUG = n

LIBRARY_NAME 	= libvideorecordcfg

SRC 		= videorecord_cfg.c

CFLAGS+= -I${SPXINC}/iniparser
CFLAGS+= -I${SPXINC}/unix
CFLAGS+= -I${SPXINC}/global
CFLAGS+= -I${SPXINC}/dbgout
CFLAGS += -I${SPXINC}/featuredefine
CFLAGS+= -I${SPXINC}/hostname

include ${TOOLDIR}/rules/Rules.make.libs

