#!/bin/sh

SET_RETRY=3
SET_TIMEOUT=3

HOST_NAME=`hostname`

DOMAIN_NAME=`grep "domain" /etc/resolv.conf | awk '{ print $2}' | tail -1`

if [ "$HOST_NAME" == "" ]; then
        echo "DHCP CONF: hostname is empty!!!"
        exit 0
fi

if [ "$DOMAIN_NAME" == "" ]; then
        FQDN=$HOST_NAME
else
        FQDN=$HOST_NAME.$DOMAIN_NAME
fi
