/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */
#ifndef AMIMIBMODULE_HOSTNAME_H
#define AMIMIBMODULE_HOSTNAME_H

/* function declarations */
void init_libsnmp_hostname_mib(void);
Netsnmp_Node_Handler handle_amiHostname;

#endif /* AMIMIBMODULE_HOSTNAME_H */
