#----------------------------------------------------------------------
#                      Makefile to build libchecksum
#                 Copyright (c) 2010 American Megatrends Inc 
#-----------------------------------------------------------------------

#------- Comment/uncomment the following line to enable/disable debugging--------------
DEBUG = n
#---------------------------------------------------------------------------------------
#---------always set target as below if you are part of libami---------------------------
LIBRARY_NAME 	= libchecksum
#----------------------------------------------------------------------------------------
#---------------------- Change according to your files ----------------------------------
SRC 		= crc32.c module100.c crc8.c	 	    # Source File

include ${TOOLDIR}/rules/Rules.make.libs

