#-------------------------------------------------------------------------------------------------------------------------
#                      Makefile to build libencryption
#                 Copyright (c) 2008 American Megatrends Inc 
#-------------------------------------------------------------------------------------------------------------------------

#------- Comment/uncomment the following line to enable/disable debugging-------------------
DEBUG = n

#---------------------- Change according to your files ---------------------------------------------------------
LIBRARY_NAME 	= libencryption

SRC +=  md2_dgst.c 

CFLAGS += -I${SPXINC}/global
CFLAGS += -I${SPXINC}/dbgout

include ${TOOLDIR}/rules/Rules.make.libs
#----------------------------------------------------------------------------------------------------------------------------
